### ISSUE TITLE
[Bug] tubemq master can not start

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#1915]
### What happened

![image](https://user-images.githubusercontent.com/18047329/144955987-219f45fd-ec26-47df-8ca7-c42271cab933.png)

### What you expected to happen

start successfully

### How to reproduce

start all the inlong modules use [`docker-compose`](https://inlong.apache.org/zh-CN/docs/next/deployment/docker)

### InLong version

master

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
Well, this error should be caused by the modification of [1]. I think the modification of [1] is not wrong, but caused by our inability to obtain the corresponding IP when constructing the Docker environment.

I am going to roll back the modification of [1], and then fill in a piece of information on how to fill in the copy of the Master node in the document [2] and [3] of the environment construction. 

I am going to do this next, if you think there is a better way, please let me know, thanks!

1.https://github.com/apache/incubator-inlong/pull/1871
2.https://inlong.apache.org/docs/modules/tubemq/quick_start
3.https://inlong.apache.org/docs/modules/tubemq/deployment
