### ISSUE TITLE
[Bug] summit job failed after enabling Prometheus

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#2094]
### What happened

![cbf14802c0141c12677e0bebba81e4b](https://user-images.githubusercontent.com/18047329/148005953-90e25600-c6a6-4f1b-a3c0-72e02bcf6a93.png)

### What you expected to happen

summit job successfully after enabling Prometheus

### How to reproduce

enable `agent.prometheus.enable` and summit a job.

### InLong version

master

### InLong Component

InLong Agent, Other for not specified component

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@shink PTAL

**Comment by shink** [comment]
It seems that this is because these metrics belong to instances rather than classes, so they will be registered repeatedly when creating multiple instances. A simple solution is to make these metrics static.

https://github.com/apache/incubator-inlong/blob/ea29797d36526f735fd7e7e4fa506430b4e79b1e/inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/metrics/SourcePrometheusMetrics.java#L31-L39
